### ISSUE TITLE
Build depends on a now deprecated gometalinter

### ISSUE THREAD

**Issue by irfn** [lostromos/lostromos#82]
# Build depends on a now deprecated gometalinter

Check the discussion happening here.
https://github.com/alecthomas/gometalinter/issues/590
The project will be archived soon. Move to https://github.com/golangci/golangci-lint

**Comment by nicolerenee** [comment]
Thanks for calling this out. I've been meaning to get this changed but have been kinda busy lately. Feel free to submit a PR, or I can work on one this weekend.
